backend:
  name: github
  repo: jadudm/cms-htmd
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Lessons
    name: lessons
    folder: _lessons/
    create: true
    slug: "{{indicator}}-{{priority}}-{{assessment}}-{{slug}}-{{course}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'widepage'}
      - {label: "Title", name: "title", widget: "string"}
      - {
        label: "Course", 
        name: "course", 
        widget: "number", 
        default: 1,
        min: 1,
        max: 12,
        value_type: "int"
        }
      - {
        label: "Indicator", 
        name: "indicator", 
        widget: "select", 
        options: ["Outcomes", "Capacity", "Visibility", "Development"]
        }
      - {
        label: "Priority", 
        name: "priority", 
        widget: "select", 
        options: ["High", "Medium", "Low"]
        }
      - { 
        label: "Assessment", 
        name: "assessment", 
        widget: "number", 
        default: 1,
        min: 1,
        max: 8,
        value_type: "int"
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
