# To run locally:
# npx netlify-cms-proxy-server 
# netlify dev
# To fix for deploy:
# Change branch to "main"
# local_backend to false

backend:
  name: github
  repo: jadudm/cms-htmd
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

# See https://www.netlifycms.org/docs/beta-features/
# local_backend: true
# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:8082/api/v1
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['ip_addr']
  
media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Course One
    name: one
    folder: collections/_one
    create: true
    # https://www.netlifycms.org/docs/beta-features/
    # slug: "{{indicator}}-{{priority}}-{{assessment}}-{{slug}}-{{course}}"
    # https://www.netlifycms.org/docs/beta-features/
    # slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'widepage'}
      - {label: "Title", name: "title", widget: "string"}
      - { 
        label: "Lesson", 
        name: "lesson", 
        widget: "number", 
        default: 1,
        min: 0,
        max: 12,
        value_type: "int"
        }
      - {
        label: "Indicator", 
        name: "indicator", 
        widget: "select", 
        options: ["outcomes", "capacity", "procurement", "development", "admin"]
        }
      - {
        label: "Priority", 
        name: "priority", 
        widget: "select", 
        options: ["high", "medium", "low"]
        }
      - {
        label: "Visibility", 
        name: "visible", 
        widget: "boolean", 
        default: true
        }

      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
