# To run locally:
# npx netlify-cms-proxy-server 
# netlify dev
# To fix for deploy:
# Change branch to "main"
# local_backend to false

backend:
  name: github
  repo: jadudm/cms-htmd
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

# See https://www.netlifycms.org/docs/beta-features/
# local_backend: true
# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:8082/api/v1
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['ip_addr']
  
media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Lessons
    label_singular: Lesson
    name: lessons
    folder: collections/_courses
    create: true
    # https://www.netlifycms.org/docs/beta-features/
    nested:
      depth: 2
      summary: "Course {{course}}"
    # slug: "{{indicator}}-{{priority}}-{{assessment}}-{{slug}}-{{course}}"
    # https://www.netlifycms.org/docs/beta-features/
    slug: "{{course}}/{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'widepage'}
      - {label: "Title", name: "title", widget: "string"}
      - {
        label: "Course", 
        name: "course", 
        widget: "number", 
        default: 1,
        min: 1,
        max: 12,
        value_type: "int"
        }
      - { 
        label: "Lesson", 
        name: "lesson", 
        widget: "number", 
        default: 1,
        min: 1,
        max: 8,
        value_type: "int"
        }
      - {
        label: "Indicator", 
        name: "indicator", 
        widget: "select", 
        options: ["Outcomes & Orientation", "State Capacity", "Procurement Flexibility", "Iterative Development", "Admin"]
        }
      - {
        label: "Priority", 
        name: "priority", 
        widget: "select", 
        options: ["High", "Medium", "Low"]
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
